spring.datasource.url=jdbc:mysql://localhost:3306/animalsdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=animals
spring.datasource.password=animals_pass
server.port=8083

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

app.jwt.secret=YjJxR3lLSXJ0eU5jVnZ2VjJSM1d5VnZkQ0xLaG5uQk9tR3R0c1p3cUx6YkE=
app.jwt.expiration=3600000
